"""Context file generator (CLAUDE.md / context.md)."""
from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone

from neuropack.types import MemoryRecord


def generate_context_markdown(
    memories: list[MemoryRecord],
    title: str = "NeuroPack Memory Context",
) -> str:
    """Generate a markdown summary from a list of memories."""
    lines: list[str] = []
    now = datetime.now(timezone.utc)

    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"*Auto-generated by NeuroPack on {now.strftime('%Y-%m-%d %H:%M UTC')}*")
    lines.append(f"*{len(memories)} memories indexed*")
    lines.append("")

    # Tag cloud
    tag_counts: Counter[str] = Counter()
    for m in memories:
        tag_counts.update(m.tags)

    if tag_counts:
        lines.append("## Tags")
        lines.append("")
        tag_strs = [f"`{tag}` ({count})" for tag, count in tag_counts.most_common(20)]
        lines.append(" | ".join(tag_strs))
        lines.append("")

    # Recent activity (L3 abstracts, newest first)
    lines.append("## Recent Activity")
    lines.append("")
    for m in memories[:20]:
        age = (now - m.created_at).total_seconds() / 3600
        if age < 1:
            age_str = f"{int(age * 60)}m ago"
        elif age < 24:
            age_str = f"{int(age)}h ago"
        else:
            age_str = f"{int(age / 24)}d ago"

        tags_str = ", ".join(f"`{t}`" for t in m.tags) if m.tags else ""
        lines.append(f"- **{m.l3_abstract}** ({age_str}) {tags_str}")
    lines.append("")

    # Key facts from highest priority memories
    priority_sorted = sorted(memories, key=lambda m: m.priority, reverse=True)
    facts: list[str] = []
    for m in priority_sorted[:10]:
        facts.extend(m.l2_facts)

    if facts:
        lines.append("## Key Facts")
        lines.append("")
        for fact in facts[:30]:
            lines.append(f"- {fact}")
        lines.append("")

    return "\n".join(lines)
